services:
    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_listener, event: prePersist, connection: default }
            - { name: doctrine.event_listener, event: onFlush, connection: default }
            - { name: doctrine.event_listener, event: loadClassMetadata, connection: default }
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_listener, event: prePersist, connection: default }
            - { name: doctrine.event_listener, event: onFlush, connection: default }
            - { name: doctrine.event_listener, event: loadClassMetadata, connection: default }
