twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: 
        - 'tailwind_2_layout.html.twig'
        - 'form/theme.html.twig'
        - '@SonataFormatter/Form/formatter.html.twig'
    globals:
        defaultMail: '%app.mail.default_from%'
        subscriptionMonthlyPrice: '%app.subscription.monthly_price%'
        subscriptionYearlyPrice: '%app.subscription.yearly_price%'
    file_name_pattern: "*.twig"

when@test:
    twig:
        strict_variables: true
