App\Entity\Chapter:
    exclusion_policy: all
    attributes:
        id:
            groups: ["chapter_block"]
        name:
            groups: ["chapter_block"]
        description:
            groups: ["chapter_block"]
        files:
            groups: ["chapter_block"]
        weight:
            groups: ["chapter_block"]