App\Entity\Subject:
    exclusion_policy: all
    attributes:
        id:
            groups: ["course_subject", "community_test_course_subject"]
        name:
            groups: ["course_subject", "community_test_course_subject"]